import sys

from lcd.utils.clevr import load_dataset

dataset = load_dataset(clevr=True, upscale=False, exp_path=None)
sys.path.append("/home/ubuntu/talar/talar-openreview/talar")
from ball_collect_data import features2goal

lang = features2goal(dataset[0]["obs_goal"])
anns = list(set(lang))  # annotations

tensor2lang = {}
for j, v in zip(dataset[0]["obs_goal"], anns):
    tensor2lang[str(j.int().tolist())] = v


anns = [
    "Can you help me push the blue ball behind the cyan ball",
    "Can you help me push the blue ball behind the green ball",
    "Can you help me push the blue ball behind the purple ball",
    "Can you help me push the blue ball behind the red ball",
    "Can you help me push the blue ball in front of the cyan ball",
    "Can you help me push the blue ball in front of the green ball",
    "Can you help me push the blue ball in front of the purple ball",
    "Can you help me push the blue ball in front of the red ball",
    "Can you help me push the blue ball to the left of the cyan ball",
    "Can you help me push the blue ball to the left of the green ball",
    "Can you help me push the blue ball to the left of the purple ball",
    "Can you help me push the blue ball to the left of the red ball",
    "Can you help me push the blue ball to the right of the cyan ball",
    "Can you help me push the blue ball to the right of the green ball",
    "Can you help me push the blue ball to the right of the purple ball",
    "Can you help me push the blue ball to the right of the red ball",
    "Can you help me push the cyan ball behind the blue ball",
    "Can you help me push the cyan ball behind the green ball",
    "Can you help me push the cyan ball behind the purple ball",
    "Can you help me push the cyan ball behind the red ball",
    "Can you help me push the cyan ball in front of the blue ball",
    "Can you help me push the cyan ball in front of the green ball",
    "Can you help me push the cyan ball in front of the purple ball",
    "Can you help me push the cyan ball in front of the red ball",
    "Can you help me push the cyan ball to the left of the blue ball",
    "Can you help me push the cyan ball to the left of the green ball",
    "Can you help me push the cyan ball to the left of the purple ball",
    "Can you help me push the cyan ball to the left of the red ball",
    "Can you help me push the cyan ball to the right of the blue ball",
    "Can you help me push the cyan ball to the right of the green ball",
    "Can you help me push the cyan ball to the right of the purple ball",
    "Can you help me push the cyan ball to the right of the red ball",
    "Can you help me push the green ball behind the blue ball",
    "Can you help me push the green ball behind the cyan ball",
    "Can you help me push the green ball behind the purple ball",
    "Can you help me push the green ball behind the red ball",
    "Can you help me push the green ball in front of the blue ball",
    "Can you help me push the green ball in front of the cyan ball",
    "Can you help me push the green ball in front of the purple ball",
    "Can you help me push the green ball in front of the red ball",
    "Can you help me push the green ball to the left of the blue ball",
    "Can you help me push the green ball to the left of the cyan ball",
    "Can you help me push the green ball to the left of the purple ball",
    "Can you help me push the green ball to the left of the red ball",
    "Can you help me push the green ball to the right of the blue ball",
    "Can you help me push the green ball to the right of the cyan ball",
    "Can you help me push the green ball to the right of the purple ball",
    "Can you help me push the green ball to the right of the red ball",
    "Can you help me push the purple ball behind the blue ball",
    "Can you help me push the purple ball behind the cyan ball",
    "Can you help me push the purple ball behind the green ball",
    "Can you help me push the purple ball behind the red ball",
    "Can you help me push the purple ball in front of the blue ball",
    "Can you help me push the purple ball in front of the cyan ball",
    "Can you help me push the purple ball in front of the green ball",
    "Can you help me push the purple ball in front of the red ball",
    "Can you help me push the purple ball to the left of the blue ball",
    "Can you help me push the purple ball to the left of the cyan ball",
    "Can you help me push the purple ball to the left of the green ball",
    "Can you help me push the purple ball to the left of the red ball",
    "Can you help me push the purple ball to the right of the blue ball",
    "Can you help me push the purple ball to the right of the cyan ball",
    "Can you help me push the purple ball to the right of the green ball",
    "Can you help me push the purple ball to the right of the red ball",
    "Can you help me push the red ball behind the blue ball",
    "Can you help me push the red ball behind the cyan ball",
    "Can you help me push the red ball behind the green ball",
    "Can you help me push the red ball behind the purple ball",
    "Can you help me push the red ball in front of the blue ball",
    "Can you help me push the red ball in front of the cyan ball",
    "Can you help me push the red ball in front of the green ball",
    "Can you help me push the red ball in front of the purple ball",
    "Can you help me push the red ball to the left of the blue ball",
    "Can you help me push the red ball to the left of the cyan ball",
    "Can you help me push the red ball to the left of the green ball",
    "Can you help me push the red ball to the left of the purple ball",
    "Can you help me push the red ball to the right of the blue ball",
    "Can you help me push the red ball to the right of the cyan ball",
    "Can you help me push the red ball to the right of the green ball",
    "Can you help me push the red ball to the right of the purple ball",
    "Can you push the blue ball behind the cyan ball",
    "Can you push the blue ball behind the green ball",
    "Can you push the blue ball behind the purple ball",
    "Can you push the blue ball behind the red ball",
    "Can you push the blue ball in front of the cyan ball",
    "Can you push the blue ball in front of the green ball",
    "Can you push the blue ball in front of the purple ball",
    "Can you push the blue ball in front of the red ball",
    "Can you push the blue ball to the left of the cyan ball",
    "Can you push the blue ball to the left of the green ball",
    "Can you push the blue ball to the left of the purple ball",
    "Can you push the blue ball to the left of the red ball",
    "Can you push the blue ball to the right of the cyan ball",
    "Can you push the blue ball to the right of the green ball",
    "Can you push the blue ball to the right of the purple ball",
    "Can you push the blue ball to the right of the red ball",
    "Can you push the cyan ball behind the blue ball",
    "Can you push the cyan ball behind the green ball",
    "Can you push the cyan ball behind the purple ball",
    "Can you push the cyan ball behind the red ball",
    "Can you push the cyan ball in front of the blue ball",
    "Can you push the cyan ball in front of the green ball",
    "Can you push the cyan ball in front of the purple ball",
    "Can you push the cyan ball in front of the red ball",
    "Can you push the cyan ball to the left of the blue ball",
    "Can you push the cyan ball to the left of the green ball",
    "Can you push the cyan ball to the left of the purple ball",
    "Can you push the cyan ball to the left of the red ball",
    "Can you push the cyan ball to the right of the blue ball",
    "Can you push the cyan ball to the right of the green ball",
    "Can you push the cyan ball to the right of the purple ball",
    "Can you push the cyan ball to the right of the red ball",
    "Can you push the green ball behind the blue ball",
    "Can you push the green ball behind the cyan ball",
    "Can you push the green ball behind the purple ball",
    "Can you push the green ball behind the red ball",
    "Can you push the green ball in front of the blue ball",
    "Can you push the green ball in front of the cyan ball",
    "Can you push the green ball in front of the purple ball",
    "Can you push the green ball in front of the red ball",
    "Can you push the green ball to the left of the blue ball",
    "Can you push the green ball to the left of the cyan ball",
    "Can you push the green ball to the left of the purple ball",
    "Can you push the green ball to the left of the red ball",
    "Can you push the green ball to the right of the blue ball",
    "Can you push the green ball to the right of the cyan ball",
    "Can you push the green ball to the right of the purple ball",
    "Can you push the green ball to the right of the red ball",
    "Can you push the purple ball behind the blue ball",
    "Can you push the purple ball behind the cyan ball",
    "Can you push the purple ball behind the green ball",
    "Can you push the purple ball behind the red ball",
    "Can you push the purple ball in front of the blue ball",
    "Can you push the purple ball in front of the cyan ball",
    "Can you push the purple ball in front of the green ball",
    "Can you push the purple ball in front of the red ball",
    "Can you push the purple ball to the left of the blue ball",
    "Can you push the purple ball to the left of the cyan ball",
    "Can you push the purple ball to the left of the green ball",
    "Can you push the purple ball to the left of the red ball",
    "Can you push the purple ball to the right of the blue ball",
    "Can you push the purple ball to the right of the cyan ball",
    "Can you push the purple ball to the right of the green ball",
    "Can you push the purple ball to the right of the red ball",
    "Can you push the red ball behind the blue ball",
    "Can you push the red ball behind the cyan ball",
    "Can you push the red ball behind the green ball",
    "Can you push the red ball behind the purple ball",
    "Can you push the red ball in front of the blue ball",
    "Can you push the red ball in front of the cyan ball",
    "Can you push the red ball in front of the green ball",
    "Can you push the red ball in front of the purple ball",
    "Can you push the red ball to the left of the blue ball",
    "Can you push the red ball to the left of the cyan ball",
    "Can you push the red ball to the left of the green ball",
    "Can you push the red ball to the left of the purple ball",
    "Can you push the red ball to the right of the blue ball",
    "Can you push the red ball to the right of the cyan ball",
    "Can you push the red ball to the right of the green ball",
    "Can you push the red ball to the right of the purple ball",
    "Is the blue ball behind the cyan ball",
    "Is the blue ball behind the green ball",
    "Is the blue ball behind the purple ball",
    "Is the blue ball behind the red ball",
    "Is the blue ball in front of the cyan ball",
    "Is the blue ball in front of the green ball",
    "Is the blue ball in front of the purple ball",
    "Is the blue ball in front of the red ball",
    "Is the blue ball to the left of the cyan ball",
    "Is the blue ball to the left of the green ball",
    "Is the blue ball to the left of the purple ball",
    "Is the blue ball to the left of the red ball",
    "Is the blue ball to the right of the cyan ball",
    "Is the blue ball to the right of the green ball",
    "Is the blue ball to the right of the purple ball",
    "Is the blue ball to the right of the red ball",
    "Is the cyan ball behind the blue ball",
    "Is the cyan ball behind the green ball",
    "Is the cyan ball behind the purple ball",
    "Is the cyan ball behind the red ball",
    "Is the cyan ball in front of the blue ball",
    "Is the cyan ball in front of the green ball",
    "Is the cyan ball in front of the purple ball",
    "Is the cyan ball in front of the red ball",
    "Is the cyan ball to the left of the blue ball",
    "Is the cyan ball to the left of the green ball",
    "Is the cyan ball to the left of the purple ball",
    "Is the cyan ball to the left of the red ball",
    "Is the cyan ball to the right of the blue ball",
    "Is the cyan ball to the right of the green ball",
    "Is the cyan ball to the right of the purple ball",
    "Is the cyan ball to the right of the red ball",
    "Is the green ball behind the blue ball",
    "Is the green ball behind the cyan ball",
    "Is the green ball behind the purple ball",
    "Is the green ball behind the red ball",
    "Is the green ball in front of the blue ball",
    "Is the green ball in front of the cyan ball",
    "Is the green ball in front of the purple ball",
    "Is the green ball in front of the red ball",
    "Is the green ball to the left of the blue ball",
    "Is the green ball to the left of the cyan ball",
    "Is the green ball to the left of the purple ball",
    "Is the green ball to the left of the red ball",
    "Is the green ball to the right of the blue ball",
    "Is the green ball to the right of the cyan ball",
    "Is the green ball to the right of the purple ball",
    "Is the green ball to the right of the red ball",
    "Is the purple ball behind the blue ball",
    "Is the purple ball behind the cyan ball",
    "Is the purple ball behind the green ball",
    "Is the purple ball behind the red ball",
    "Is the purple ball in front of the blue ball",
    "Is the purple ball in front of the cyan ball",
    "Is the purple ball in front of the green ball",
    "Is the purple ball in front of the red ball",
    "Is the purple ball to the left of the blue ball",
    "Is the purple ball to the left of the cyan ball",
    "Is the purple ball to the left of the green ball",
    "Is the purple ball to the left of the red ball",
    "Is the purple ball to the right of the blue ball",
    "Is the purple ball to the right of the cyan ball",
    "Is the purple ball to the right of the green ball",
    "Is the purple ball to the right of the red ball",
    "Is the red ball behind the blue ball",
    "Is the red ball behind the cyan ball",
    "Is the red ball behind the green ball",
    "Is the red ball behind the purple ball",
    "Is the red ball in front of the blue ball",
    "Is the red ball in front of the cyan ball",
    "Is the red ball in front of the green ball",
    "Is the red ball in front of the purple ball",
    "Is the red ball to the left of the blue ball",
    "Is the red ball to the left of the cyan ball",
    "Is the red ball to the left of the green ball",
    "Is the red ball to the left of the purple ball",
    "Is the red ball to the right of the blue ball",
    "Is the red ball to the right of the cyan ball",
    "Is the red ball to the right of the green ball",
    "Is the red ball to the right of the purple ball",
    "Is there any blue ball behind the cyan ball",
    "Is there any blue ball behind the green ball",
    "Is there any blue ball behind the purple ball",
    "Is there any blue ball behind the red ball",
    "Is there any blue ball in front of the cyan ball",
    "Is there any blue ball in front of the green ball",
    "Is there any blue ball in front of the purple ball",
    "Is there any blue ball in front of the red ball",
    "Is there any blue ball to the left of the cyan ball",
    "Is there any blue ball to the left of the green ball",
    "Is there any blue ball to the left of the purple ball",
    "Is there any blue ball to the left of the red ball",
    "Is there any blue ball to the right of the cyan ball",
    "Is there any blue ball to the right of the green ball",
    "Is there any blue ball to the right of the purple ball",
    "Is there any blue ball to the right of the red ball",
    "Is there any cyan ball behind the blue ball",
    "Is there any cyan ball behind the green ball",
    "Is there any cyan ball behind the purple ball",
    "Is there any cyan ball behind the red ball",
    "Is there any cyan ball in front of the blue ball",
    "Is there any cyan ball in front of the green ball",
    "Is there any cyan ball in front of the purple ball",
    "Is there any cyan ball in front of the red ball",
    "Is there any cyan ball to the left of the blue ball",
    "Is there any cyan ball to the left of the green ball",
    "Is there any cyan ball to the left of the purple ball",
    "Is there any cyan ball to the left of the red ball",
    "Is there any cyan ball to the right of the blue ball",
    "Is there any cyan ball to the right of the green ball",
    "Is there any cyan ball to the right of the purple ball",
    "Is there any cyan ball to the right of the red ball",
    "Is there any green ball behind the blue ball",
    "Is there any green ball behind the cyan ball",
    "Is there any green ball behind the purple ball",
    "Is there any green ball behind the red ball",
    "Is there any green ball in front of the blue ball",
    "Is there any green ball in front of the cyan ball",
    "Is there any green ball in front of the purple ball",
    "Is there any green ball in front of the red ball",
    "Is there any green ball to the left of the blue ball",
    "Is there any green ball to the left of the cyan ball",
    "Is there any green ball to the left of the purple ball",
    "Is there any green ball to the left of the red ball",
    "Is there any green ball to the right of the blue ball",
    "Is there any green ball to the right of the cyan ball",
    "Is there any green ball to the right of the purple ball",
    "Is there any green ball to the right of the red ball",
    "Is there any purple ball behind the blue ball",
    "Is there any purple ball behind the cyan ball",
    "Is there any purple ball behind the green ball",
    "Is there any purple ball behind the red ball",
    "Is there any purple ball in front of the blue ball",
    "Is there any purple ball in front of the cyan ball",
    "Is there any purple ball in front of the green ball",
    "Is there any purple ball in front of the red ball",
    "Is there any purple ball to the left of the blue ball",
    "Is there any purple ball to the left of the cyan ball",
    "Is there any purple ball to the left of the green ball",
    "Is there any purple ball to the left of the red ball",
    "Is there any purple ball to the right of the blue ball",
    "Is there any purple ball to the right of the cyan ball",
    "Is there any purple ball to the right of the green ball",
    "Is there any purple ball to the right of the red ball",
    "Is there any red ball behind the blue ball",
    "Is there any red ball behind the cyan ball",
    "Is there any red ball behind the green ball",
    "Is there any red ball behind the purple ball",
    "Is there any red ball in front of the blue ball",
    "Is there any red ball in front of the cyan ball",
    "Is there any red ball in front of the green ball",
    "Is there any red ball in front of the purple ball",
    "Is there any red ball to the left of the blue ball",
    "Is there any red ball to the left of the cyan ball",
    "Is there any red ball to the left of the green ball",
    "Is there any red ball to the left of the purple ball",
    "Is there any red ball to the right of the blue ball",
    "Is there any red ball to the right of the cyan ball",
    "Is there any red ball to the right of the green ball",
    "Is there any red ball to the right of the purple ball",
    "Push the blue ball behind the cyan ball",
    "Push the blue ball behind the green ball",
    "Push the blue ball behind the purple ball",
    "Push the blue ball behind the red ball",
    "Push the blue ball in front of the cyan ball",
    "Push the blue ball in front of the green ball",
    "Push the blue ball in front of the purple ball",
    "Push the blue ball in front of the red ball",
    "Push the blue ball to the left of the cyan ball",
    "Push the blue ball to the left of the green ball",
    "Push the blue ball to the left of the purple ball",
    "Push the blue ball to the left of the red ball",
    "Push the blue ball to the right of the cyan ball",
    "Push the blue ball to the right of the green ball",
    "Push the blue ball to the right of the purple ball",
    "Push the blue ball to the right of the red ball",
    "Push the cyan ball behind the blue ball",
    "Push the cyan ball behind the green ball",
    "Push the cyan ball behind the purple ball",
    "Push the cyan ball behind the red ball",
    "Push the cyan ball in front of the blue ball",
    "Push the cyan ball in front of the green ball",
    "Push the cyan ball in front of the purple ball",
    "Push the cyan ball in front of the red ball",
    "Push the cyan ball to the left of the blue ball",
    "Push the cyan ball to the left of the green ball",
    "Push the cyan ball to the left of the purple ball",
    "Push the cyan ball to the left of the red ball",
    "Push the cyan ball to the right of the blue ball",
    "Push the cyan ball to the right of the green ball",
    "Push the cyan ball to the right of the purple ball",
    "Push the cyan ball to the right of the red ball",
    "Push the green ball behind the blue ball",
    "Push the green ball behind the cyan ball",
    "Push the green ball behind the purple ball",
    "Push the green ball behind the red ball",
    "Push the green ball in front of the blue ball",
    "Push the green ball in front of the cyan ball",
    "Push the green ball in front of the purple ball",
    "Push the green ball in front of the red ball",
    "Push the green ball to the left of the blue ball",
    "Push the green ball to the left of the cyan ball",
    "Push the green ball to the left of the purple ball",
    "Push the green ball to the left of the red ball",
    "Push the green ball to the right of the blue ball",
    "Push the green ball to the right of the cyan ball",
    "Push the green ball to the right of the purple ball",
    "Push the green ball to the right of the red ball",
    "Push the purple ball behind the blue ball",
    "Push the purple ball behind the cyan ball",
    "Push the purple ball behind the green ball",
    "Push the purple ball behind the red ball",
    "Push the purple ball in front of the blue ball",
    "Push the purple ball in front of the cyan ball",
    "Push the purple ball in front of the green ball",
    "Push the purple ball in front of the red ball",
    "Push the purple ball to the left of the blue ball",
    "Push the purple ball to the left of the cyan ball",
    "Push the purple ball to the left of the green ball",
    "Push the purple ball to the left of the red ball",
    "Push the purple ball to the right of the blue ball",
    "Push the purple ball to the right of the cyan ball",
    "Push the purple ball to the right of the green ball",
    "Push the purple ball to the right of the red ball",
    "Push the red ball behind the blue ball",
    "Push the red ball behind the cyan ball",
    "Push the red ball behind the green ball",
    "Push the red ball behind the purple ball",
    "Push the red ball in front of the blue ball",
    "Push the red ball in front of the cyan ball",
    "Push the red ball in front of the green ball",
    "Push the red ball in front of the purple ball",
    "Push the red ball to the left of the blue ball",
    "Push the red ball to the left of the cyan ball",
    "Push the red ball to the left of the green ball",
    "Push the red ball to the left of the purple ball",
    "Push the red ball to the right of the blue ball",
    "Push the red ball to the right of the cyan ball",
    "Push the red ball to the right of the green ball",
    "Push the red ball to the right of the purple ball",
    "The blue ball is being pushed behind the cyan ball",
    "The blue ball is being pushed behind the green ball",
    "The blue ball is being pushed behind the purple ball",
    "The blue ball is being pushed behind the red ball",
    "The blue ball is being pushed in front of the cyan ball",
    "The blue ball is being pushed in front of the green ball",
    "The blue ball is being pushed in front of the purple ball",
    "The blue ball is being pushed in front of the red ball",
    "The blue ball is being pushed to the left of the cyan ball",
    "The blue ball is being pushed to the left of the green ball",
    "The blue ball is being pushed to the left of the purple ball",
    "The blue ball is being pushed to the left of the red ball",
    "The blue ball is being pushed to the right of the cyan ball",
    "The blue ball is being pushed to the right of the green ball",
    "The blue ball is being pushed to the right of the purple ball",
    "The blue ball is being pushed to the right of the red ball",
    "The blue ball is pushed behind the cyan ball",
    "The blue ball is pushed behind the green ball",
    "The blue ball is pushed behind the purple ball",
    "The blue ball is pushed behind the red ball",
    "The blue ball is pushed in front of the cyan ball",
    "The blue ball is pushed in front of the green ball",
    "The blue ball is pushed in front of the purple ball",
    "The blue ball is pushed in front of the red ball",
    "The blue ball is pushed to the left of the cyan ball",
    "The blue ball is pushed to the left of the green ball",
    "The blue ball is pushed to the left of the purple ball",
    "The blue ball is pushed to the left of the red ball",
    "The blue ball is pushed to the right of the cyan ball",
    "The blue ball is pushed to the right of the green ball",
    "The blue ball is pushed to the right of the purple ball",
    "The blue ball is pushed to the right of the red ball",
    "The blue ball moves behind the cyan ball",
    "The blue ball moves behind the green ball",
    "The blue ball moves behind the purple ball",
    "The blue ball moves behind the red ball",
    "The blue ball moves in front of the cyan ball",
    "The blue ball moves in front of the green ball",
    "The blue ball moves in front of the purple ball",
    "The blue ball moves in front of the red ball",
    "The blue ball moves to the left of the cyan ball",
    "The blue ball moves to the left of the green ball",
    "The blue ball moves to the left of the purple ball",
    "The blue ball moves to the left of the red ball",
    "The blue ball moves to the right of the cyan ball",
    "The blue ball moves to the right of the green ball",
    "The blue ball moves to the right of the purple ball",
    "The blue ball moves to the right of the red ball",
    "The blue ball was moved behind the cyan ball",
    "The blue ball was moved behind the green ball",
    "The blue ball was moved behind the purple ball",
    "The blue ball was moved behind the red ball",
    "The blue ball was moved in front of the cyan ball",
    "The blue ball was moved in front of the green ball",
    "The blue ball was moved in front of the purple ball",
    "The blue ball was moved in front of the red ball",
    "The blue ball was moved to the left of the cyan ball",
    "The blue ball was moved to the left of the green ball",
    "The blue ball was moved to the left of the purple ball",
    "The blue ball was moved to the left of the red ball",
    "The blue ball was moved to the right of the cyan ball",
    "The blue ball was moved to the right of the green ball",
    "The blue ball was moved to the right of the purple ball",
    "The blue ball was moved to the right of the red ball",
    "The cyan ball is being pushed behind the blue ball",
    "The cyan ball is being pushed behind the green ball",
    "The cyan ball is being pushed behind the purple ball",
    "The cyan ball is being pushed behind the red ball",
    "The cyan ball is being pushed in front of the blue ball",
    "The cyan ball is being pushed in front of the green ball",
    "The cyan ball is being pushed in front of the purple ball",
    "The cyan ball is being pushed in front of the red ball",
    "The cyan ball is being pushed to the left of the blue ball",
    "The cyan ball is being pushed to the left of the green ball",
    "The cyan ball is being pushed to the left of the purple ball",
    "The cyan ball is being pushed to the left of the red ball",
    "The cyan ball is being pushed to the right of the blue ball",
    "The cyan ball is being pushed to the right of the green ball",
    "The cyan ball is being pushed to the right of the purple ball",
    "The cyan ball is being pushed to the right of the red ball",
    "The cyan ball is pushed behind the blue ball",
    "The cyan ball is pushed behind the green ball",
    "The cyan ball is pushed behind the purple ball",
    "The cyan ball is pushed behind the red ball",
    "The cyan ball is pushed in front of the blue ball",
    "The cyan ball is pushed in front of the green ball",
    "The cyan ball is pushed in front of the purple ball",
    "The cyan ball is pushed in front of the red ball",
    "The cyan ball is pushed to the left of the blue ball",
    "The cyan ball is pushed to the left of the green ball",
    "The cyan ball is pushed to the left of the purple ball",
    "The cyan ball is pushed to the left of the red ball",
    "The cyan ball is pushed to the right of the blue ball",
    "The cyan ball is pushed to the right of the green ball",
    "The cyan ball is pushed to the right of the purple ball",
    "The cyan ball is pushed to the right of the red ball",
    "The cyan ball moves behind the blue ball",
    "The cyan ball moves behind the green ball",
    "The cyan ball moves behind the purple ball",
    "The cyan ball moves behind the red ball",
    "The cyan ball moves in front of the blue ball",
    "The cyan ball moves in front of the green ball",
    "The cyan ball moves in front of the purple ball",
    "The cyan ball moves in front of the red ball",
    "The cyan ball moves to the left of the blue ball",
    "The cyan ball moves to the left of the green ball",
    "The cyan ball moves to the left of the purple ball",
    "The cyan ball moves to the left of the red ball",
    "The cyan ball moves to the right of the blue ball",
    "The cyan ball moves to the right of the green ball",
    "The cyan ball moves to the right of the purple ball",
    "The cyan ball moves to the right of the red ball",
    "The cyan ball was moved behind the blue ball",
    "The cyan ball was moved behind the green ball",
    "The cyan ball was moved behind the purple ball",
    "The cyan ball was moved behind the red ball",
    "The cyan ball was moved in front of the blue ball",
    "The cyan ball was moved in front of the green ball",
    "The cyan ball was moved in front of the purple ball",
    "The cyan ball was moved in front of the red ball",
    "The cyan ball was moved to the left of the blue ball",
    "The cyan ball was moved to the left of the green ball",
    "The cyan ball was moved to the left of the purple ball",
    "The cyan ball was moved to the left of the red ball",
    "The cyan ball was moved to the right of the blue ball",
    "The cyan ball was moved to the right of the green ball",
    "The cyan ball was moved to the right of the purple ball",
    "The cyan ball was moved to the right of the red ball",
    "The green ball is being pushed behind the blue ball",
    "The green ball is being pushed behind the cyan ball",
    "The green ball is being pushed behind the purple ball",
    "The green ball is being pushed behind the red ball",
    "The green ball is being pushed in front of the blue ball",
    "The green ball is being pushed in front of the cyan ball",
    "The green ball is being pushed in front of the purple ball",
    "The green ball is being pushed in front of the red ball",
    "The green ball is being pushed to the left of the blue ball",
    "The green ball is being pushed to the left of the cyan ball",
    "The green ball is being pushed to the left of the purple ball",
    "The green ball is being pushed to the left of the red ball",
    "The green ball is being pushed to the right of the blue ball",
    "The green ball is being pushed to the right of the cyan ball",
    "The green ball is being pushed to the right of the purple ball",
    "The green ball is being pushed to the right of the red ball",
    "The green ball is pushed behind the blue ball",
    "The green ball is pushed behind the cyan ball",
    "The green ball is pushed behind the purple ball",
    "The green ball is pushed behind the red ball",
    "The green ball is pushed in front of the blue ball",
    "The green ball is pushed in front of the cyan ball",
    "The green ball is pushed in front of the purple ball",
    "The green ball is pushed in front of the red ball",
    "The green ball is pushed to the left of the blue ball",
    "The green ball is pushed to the left of the cyan ball",
    "The green ball is pushed to the left of the purple ball",
    "The green ball is pushed to the left of the red ball",
    "The green ball is pushed to the right of the blue ball",
    "The green ball is pushed to the right of the cyan ball",
    "The green ball is pushed to the right of the purple ball",
    "The green ball is pushed to the right of the red ball",
    "The green ball moves behind the blue ball",
    "The green ball moves behind the cyan ball",
    "The green ball moves behind the purple ball",
    "The green ball moves behind the red ball",
    "The green ball moves in front of the blue ball",
    "The green ball moves in front of the cyan ball",
    "The green ball moves in front of the purple ball",
    "The green ball moves in front of the red ball",
    "The green ball moves to the left of the blue ball",
    "The green ball moves to the left of the cyan ball",
    "The green ball moves to the left of the purple ball",
    "The green ball moves to the left of the red ball",
    "The green ball moves to the right of the blue ball",
    "The green ball moves to the right of the cyan ball",
    "The green ball moves to the right of the purple ball",
    "The green ball moves to the right of the red ball",
    "The green ball was moved behind the blue ball",
    "The green ball was moved behind the cyan ball",
    "The green ball was moved behind the purple ball",
    "The green ball was moved behind the red ball",
    "The green ball was moved in front of the blue ball",
    "The green ball was moved in front of the cyan ball",
    "The green ball was moved in front of the purple ball",
    "The green ball was moved in front of the red ball",
    "The green ball was moved to the left of the blue ball",
    "The green ball was moved to the left of the cyan ball",
    "The green ball was moved to the left of the purple ball",
    "The green ball was moved to the left of the red ball",
    "The green ball was moved to the right of the blue ball",
    "The green ball was moved to the right of the cyan ball",
    "The green ball was moved to the right of the purple ball",
    "The green ball was moved to the right of the red ball",
    "The purple ball is being pushed behind the blue ball",
    "The purple ball is being pushed behind the cyan ball",
    "The purple ball is being pushed behind the green ball",
    "The purple ball is being pushed behind the red ball",
    "The purple ball is being pushed in front of the blue ball",
    "The purple ball is being pushed in front of the cyan ball",
    "The purple ball is being pushed in front of the green ball",
    "The purple ball is being pushed in front of the red ball",
    "The purple ball is being pushed to the left of the blue ball",
    "The purple ball is being pushed to the left of the cyan ball",
    "The purple ball is being pushed to the left of the green ball",
    "The purple ball is being pushed to the left of the red ball",
    "The purple ball is being pushed to the right of the blue ball",
    "The purple ball is being pushed to the right of the cyan ball",
    "The purple ball is being pushed to the right of the green ball",
    "The purple ball is being pushed to the right of the red ball",
    "The purple ball is pushed behind the blue ball",
    "The purple ball is pushed behind the cyan ball",
    "The purple ball is pushed behind the green ball",
    "The purple ball is pushed behind the red ball",
    "The purple ball is pushed in front of the blue ball",
    "The purple ball is pushed in front of the cyan ball",
    "The purple ball is pushed in front of the green ball",
    "The purple ball is pushed in front of the red ball",
    "The purple ball is pushed to the left of the blue ball",
    "The purple ball is pushed to the left of the cyan ball",
    "The purple ball is pushed to the left of the green ball",
    "The purple ball is pushed to the left of the red ball",
    "The purple ball is pushed to the right of the blue ball",
    "The purple ball is pushed to the right of the cyan ball",
    "The purple ball is pushed to the right of the green ball",
    "The purple ball is pushed to the right of the red ball",
    "The purple ball moves behind the blue ball",
    "The purple ball moves behind the cyan ball",
    "The purple ball moves behind the green ball",
    "The purple ball moves behind the red ball",
    "The purple ball moves in front of the blue ball",
    "The purple ball moves in front of the cyan ball",
    "The purple ball moves in front of the green ball",
    "The purple ball moves in front of the red ball",
    "The purple ball moves to the left of the blue ball",
    "The purple ball moves to the left of the cyan ball",
    "The purple ball moves to the left of the green ball",
    "The purple ball moves to the left of the red ball",
    "The purple ball moves to the right of the blue ball",
    "The purple ball moves to the right of the cyan ball",
    "The purple ball moves to the right of the green ball",
    "The purple ball moves to the right of the red ball",
    "The purple ball was moved behind the blue ball",
    "The purple ball was moved behind the cyan ball",
    "The purple ball was moved behind the green ball",
    "The purple ball was moved behind the red ball",
    "The purple ball was moved in front of the blue ball",
    "The purple ball was moved in front of the cyan ball",
    "The purple ball was moved in front of the green ball",
    "The purple ball was moved in front of the red ball",
    "The purple ball was moved to the left of the blue ball",
    "The purple ball was moved to the left of the cyan ball",
    "The purple ball was moved to the left of the green ball",
    "The purple ball was moved to the left of the red ball",
    "The purple ball was moved to the right of the blue ball",
    "The purple ball was moved to the right of the cyan ball",
    "The purple ball was moved to the right of the green ball",
    "The purple ball was moved to the right of the red ball",
    "The red ball is being pushed behind the blue ball",
    "The red ball is being pushed behind the cyan ball",
    "The red ball is being pushed behind the green ball",
    "The red ball is being pushed behind the purple ball",
    "The red ball is being pushed in front of the blue ball",
    "The red ball is being pushed in front of the cyan ball",
    "The red ball is being pushed in front of the green ball",
    "The red ball is being pushed in front of the purple ball",
    "The red ball is being pushed to the left of the blue ball",
    "The red ball is being pushed to the left of the cyan ball",
    "The red ball is being pushed to the left of the green ball",
    "The red ball is being pushed to the left of the purple ball",
    "The red ball is being pushed to the right of the blue ball",
    "The red ball is being pushed to the right of the cyan ball",
    "The red ball is being pushed to the right of the green ball",
    "The red ball is being pushed to the right of the purple ball",
    "The red ball is pushed behind the blue ball",
    "The red ball is pushed behind the cyan ball",
    "The red ball is pushed behind the green ball",
    "The red ball is pushed behind the purple ball",
    "The red ball is pushed in front of the blue ball",
    "The red ball is pushed in front of the cyan ball",
    "The red ball is pushed in front of the green ball",
    "The red ball is pushed in front of the purple ball",
    "The red ball is pushed to the left of the blue ball",
    "The red ball is pushed to the left of the cyan ball",
    "The red ball is pushed to the left of the green ball",
    "The red ball is pushed to the left of the purple ball",
    "The red ball is pushed to the right of the blue ball",
    "The red ball is pushed to the right of the cyan ball",
    "The red ball is pushed to the right of the green ball",
    "The red ball is pushed to the right of the purple ball",
    "The red ball moves behind the blue ball",
    "The red ball moves behind the cyan ball",
    "The red ball moves behind the green ball",
    "The red ball moves behind the purple ball",
    "The red ball moves in front of the blue ball",
    "The red ball moves in front of the cyan ball",
    "The red ball moves in front of the green ball",
    "The red ball moves in front of the purple ball",
    "The red ball moves to the left of the blue ball",
    "The red ball moves to the left of the cyan ball",
    "The red ball moves to the left of the green ball",
    "The red ball moves to the left of the purple ball",
    "The red ball moves to the right of the blue ball",
    "The red ball moves to the right of the cyan ball",
    "The red ball moves to the right of the green ball",
    "The red ball moves to the right of the purple ball",
    "The red ball was moved behind the blue ball",
    "The red ball was moved behind the cyan ball",
    "The red ball was moved behind the green ball",
    "The red ball was moved behind the purple ball",
    "The red ball was moved in front of the blue ball",
    "The red ball was moved in front of the cyan ball",
    "The red ball was moved in front of the green ball",
    "The red ball was moved in front of the purple ball",
    "The red ball was moved to the left of the blue ball",
    "The red ball was moved to the left of the cyan ball",
    "The red ball was moved to the left of the green ball",
    "The red ball was moved to the left of the purple ball",
    "The red ball was moved to the right of the blue ball",
    "The red ball was moved to the right of the cyan ball",
    "The red ball was moved to the right of the green ball",
    "The red ball was moved to the right of the purple ball",
]
